apiVersion: batch/v1
kind: CronJob
metadata:
  name: ua-cronjob
  namespace: sports-namespace
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          # - name: hello
          #   image: busybox:1.28
          #   imagePullPolicy: IfNotPresent
          #   command:
          #   - /bin/sh
          #   - -c
          #   - date; echo Hello from the Kubernetes cluster
          # restartPolicy: OnFailure
          - name: ua
            image: guimassoqueto/ua:latest
            imagePullPolicy: IfNotPresent
            command:
            - python
            - main.py
            envFrom:
              - configMapRef:
                  name: ua-configmap
          restartPolicy: OnFailure
