apiVersion: batch/v1
kind: CronJob
metadata:
  name: ua-cronjob
  namespace: sports-namespace
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ua
            image: guimassoqueto/ua:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: ua-configmap
          restartPolicy: OnFailure
